branches:
  only:
    - master
    - develop
skip_commits:
  files:
  - '*.md'

image: Visual Studio 2017

install:
  - ps: Install-Product node 8 x86
  - ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex

before_build:
  - nuget restore -Verbosity quiet

build_script:
  - cd Microsoft.VisualStudio.Terminal
  - npm install
  - cd ..
  - msbuild .\TermWindow.sln /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m /t:build

deploy_script:
  - ps: If ($env:APPVEYOR_REPO_BRANCH -Match "master") { Vsix-PublishToGallery -path '.\Microsoft.VisualStudio.Terminal\**\*.vsix' }

artifacts:
  - path: '.\Microsoft.VisualStudio.Terminal\**\*.vsix'
    name: WhackWhackTerminal
  - path: '.\Microsoft.VisualStudio.Terminal.Embeddable\**\*.nupkg'
    name: NuGet Package